'use strict';
const $ = (id) => document.getElementById(id);
const els = Object.fromEntries(['fileInput','fileName','message','workspace','originalCanvas','selectionCanvas','selectionInfo','resetSelection','cropOriginal','cropCleaned','radius','threshold','minAgree','iterations','includeAlpha','opaqueOnly','applyCleanup','downloadCleaned','reduceTargetColors','reduceAlgorithm','reduceDithering','alphaCutoffControl','alphaCutoff','alphaCutoffValue','sampleStepControl','sampleStep','sampleStepValue','reduceStatus','reducePaletteStrip','reduceSourceCanvas','reducePreviewCanvas','previewReduced','applyReduced','downloadReduced','resizeStatus','resultCanvas','resultLabel','downloadCurrent','colorTolerance','colorToleranceValue','feather','featherValue','removeConnected','paletteOptions','usePalette','paletteNote','palettePreview','paletteCanvas','metadata','scanlineStatus','scanlineCounts','scanlineCanvas'].map(id => [id,$(id)]));
const originalCtx = els.originalCanvas.getContext('2d', { willReadFrequently:true });
const selectionCtx = els.selectionCanvas.getContext('2d');
const resultCtx = els.resultCanvas.getContext('2d', { willReadFrequently:true });
const reduceSourceCtx = els.reduceSourceCanvas.getContext('2d');
const reducePreviewCtx = els.reducePreviewCanvas.getContext('2d');
const paletteCtx = els.paletteCanvas.getContext('2d');
const scanlineCtx = els.scanlineCanvas.getContext('2d');
const cropOriginalCtx = els.cropOriginal.getContext('2d', { willReadFrequently:true });
const cropCleanedCtx = els.cropCleaned.getContext('2d');
const worker = new Worker('worker.js');
let originalImage = null, currentImage = null, rotationSourceImage = null, currentRotation = 0, resizeModeTouched = false, cleanedImage = null, originalPalette = null, paletteImage = null, reducedImage = null, reducedPaletteImage = null, currentAppliedReduction = null, currentName = 'result', sourceFileName = 'image.png', reductionTargetGeneration = 0, reductionTargetsAvailable = false, buttonsDisabled = false, selection = null, dragStart = null, touchStart = null, taskId = 0, uploadGeneration = 0, debounceTimer;
const pending = new Map();
worker.onmessage = ({ data }) => { const request = pending.get(data.id); if (!request) return; pending.delete(data.id); data.error ? request.reject(new Error(data.error)) : request.resolve(data); };

function message(text, kind='') { els.message.textContent = text; els.message.className = `message ${kind}`; }
function updateReductionControlState() { const disabled=buttonsDisabled||!reductionTargetsAvailable; els.reduceTargetColors.disabled=disabled; [els.previewReduced,els.applyReduced].forEach(button=>button.disabled=disabled); }
function disableButtons(disabled) { buttonsDisabled=disabled; document.querySelectorAll('button').forEach(button => button.disabled = disabled); updateReductionControlState(); }
function busy(text) { message(`Working: ${text}…`); disableButtons(true); }
function done(text) { message(text); disableButtons(false); }
function fail(error) { message(error.message || String(error), 'error'); disableButtons(false); }
function imageDataCopy(image) { return new ImageData(new Uint8ClampedArray(image.data), image.width, image.height); }
function normalizeTransparentPixels(image) { for(let i=0;i<image.data.length;i+=4) if(image.data[i+3]===0) image.data[i]=image.data[i+1]=image.data[i+2]=0; return image; }
function runCleanup(image, options) { return new Promise((resolve,reject) => { const id = ++taskId; const pixels = new Uint8ClampedArray(image.data); pending.set(id,{resolve:data=>resolve(new Uint8ClampedArray(data.pixels)),reject}); worker.postMessage({ id, action:'cleanup', pixels:pixels.buffer, width:image.width, height:image.height, options }, [pixels.buffer]); }); }
function countUniqueColors(image) { return new Promise((resolve,reject) => { const id = ++taskId; const pixels = new Uint8ClampedArray(image.data); pending.set(id,{resolve:data=>resolve(data.count),reject}); worker.postMessage({ id, action:'countColors', pixels:pixels.buffer }, [pixels.buffer]); }); }
function runPaletteReduction(image, options) { return new Promise((resolve,reject) => { const id = ++taskId; const pixels = new Uint8ClampedArray(image.data); pending.set(id,{resolve:data=>resolve({ image:new ImageData(new Uint8ClampedArray(data.pixels), image.width, image.height), indexed:{ palette:data.palette, indices:new Uint8Array(data.indices) }, stats:data.stats }),reject}); worker.postMessage({ id, action:'paletteReduction', pixels:pixels.buffer, width:image.width, height:image.height, options }, [pixels.buffer]); }); }
function options() { return { radius:+els.radius.value, threshold:+els.threshold.value, minAgree:+els.minAgree.value, iterations:+els.iterations.value, includeAlpha:els.includeAlpha.checked, opaqueOnly:els.opaqueOnly.checked }; }
function reductionOptions() { return { targetColors:+els.reduceTargetColors.value, algorithm:els.reduceAlgorithm.value, dithering:els.reduceDithering.value, alphaCutoff:+els.alphaCutoff.value, sampleStep:+els.sampleStep.value }; }
function setCanvasImage(canvas, ctx, image) { canvas.width=image.width; canvas.height=image.height; ctx.putImageData(image,0,0); }
function colorDistance(a,b){ const dr=a[0]-b[0],dg=a[1]-b[1],db=a[2]-b[2],da=a[3]-b[3]; return dr*dr+dg*dg+db*db+da*da; }
function paletteForImage(image){
  const palette=originalPalette.map(color=>color.slice());
  const needsTransparent=image.data.some((value,index)=>index%4===3&&value===0);
  let transparent=palette.findIndex(color=>color[3]===0);
  if(needsTransparent&&transparent<0){ if(palette.length===256)return null; transparent=palette.length;palette.push([0,0,0,0]); }
  if(transparent>=0)palette[transparent]=[0,0,0,0];
  const indices=new Uint8Array(image.width*image.height), cache=new Map();
  for(let p=0,i=0;p<image.data.length;p+=4,i++){
    const color=[image.data[p],image.data[p+1],image.data[p+2],image.data[p+3]];
    if(color[3]===0){indices[i]=transparent;continue;}
    const key=color.join(','); let best=cache.get(key);
    if(best===undefined){let distance=Infinity; for(let n=0;n<palette.length;n++){if(n===transparent)continue;const candidate=colorDistance(color,palette[n]);if(candidate<distance){distance=candidate;best=n;}} cache.set(key,best);}
    indices[i]=best;
  }
  return {palette,indices};
}
function indexedPreview(image,indexed){const pixels=new Uint8ClampedArray(image.data.length); for(let i=0;i<indexed.indices.length;i++) pixels.set(indexed.palette[indexed.indices[i]],i*4); return new ImageData(pixels,image.width,image.height);}
function updateResultPreviews(){
  setCanvasImage(els.resultCanvas,resultCtx,currentImage);
  setCanvasImage(els.reduceSourceCanvas,reduceSourceCtx,currentImage);
  els.paletteOptions.hidden=!originalPalette;
  if(!originalPalette){paletteImage=null;els.palettePreview.hidden=true;return;}
  paletteImage=paletteForImage(currentImage); els.usePalette.disabled=!paletteImage;
  if(!paletteImage){els.usePalette.checked=false;els.palettePreview.hidden=true;updatePaletteNote();return;}
  els.palettePreview.hidden=false; setCanvasImage(els.paletteCanvas,paletteCtx,indexedPreview(currentImage,paletteImage)); updatePaletteNote();
}
function updatePaletteNote(){ if(!originalPalette)return; els.paletteNote.textContent=!paletteImage?'This edit needs transparency, but the source palette already uses all 256 entries. The download will fall back to truecolor + alpha to avoid a lossy palette replacement.':els.usePalette.checked?'The download will remain indexed-color. Compare both previews: palette mapping can slightly change edited colors.':'The download will be converted from indexed-color to truecolor + alpha.'; }
function clearReductionState(clearApplied=true){ reducedImage=null; reducedPaletteImage=null; if(clearApplied)currentAppliedReduction=null; els.reducePreviewCanvas.width=0; els.reducePreviewCanvas.height=0; els.reducePaletteStrip.hidden=true; els.reducePaletteStrip.innerHTML=''; els.reduceStatus.textContent='Preview a reduced palette before applying it to the current result.'; }
function paletteChip(color,index){ const translucent=color[3]<255?' translucent':''; return `<span class="palette-chip${translucent}" title="${index}: rgba(${color.join(', ')})" style="--chip:rgba(${color.join(',')})"></span>`; }
function paletteStrip(palette){ return `<div class="palette-strip" aria-label="Palette colors">${palette.map(paletteChip).join('')}</div>`; }
function showReductionPalette(indexed){ els.reducePaletteStrip.hidden=false; els.reducePaletteStrip.innerHTML=indexed.palette.map(paletteChip).join(''); }
function reductionSummary(result){ const stats=result.stats; return `${stats.actualPaletteSize.toLocaleString()} palette colors generated from ${stats.uniqueSourceColors.toLocaleString()} opaque source RGB colors. ${stats.transparentPixels.toLocaleString()} pixels were mapped to transparent by the alpha cutoff.`; }
function showCurrent(image, name) { currentImage=normalizeTransparentPixels(imageDataCopy(image)); currentName=name; updateResultPreviews(); refreshReductionTargets(currentImage); els.resultLabel.innerHTML=`Current download: <strong>${name}</strong> · ${image.width} × ${image.height}px`; }

const reductionTargets=[2,4,16,256];
async function refreshReductionTargets(image){
  const generation=++reductionTargetGeneration;
  reductionTargetsAvailable=false;
  updateReductionControlState();
  try {
    const colorCount=await countUniqueColors(image);
    if(generation!==reductionTargetGeneration||image!==currentImage)return;
    const previous=+els.reduceTargetColors.value, available=reductionTargets.filter(target=>target<colorCount);
    els.reduceTargetColors.innerHTML=available.map(target=>`<option value="${target}">${target}</option>`).join('');
    if(available.includes(previous))els.reduceTargetColors.value=String(previous);
    else if(available.length)els.reduceTargetColors.value=String(available[available.length-1]);
    reductionTargetsAvailable=available.length>0;
    updateReductionControlState();
    if(!available.length)els.reduceStatus.textContent=`This image already has ${colorCount.toLocaleString()} colors, so none of the available targets would reduce it.`;
  } catch(error){
    if(generation===reductionTargetGeneration)els.reduceStatus.textContent=`Could not determine valid reduction targets: ${error.message}`;
  }
}
function rotateImage(image, angle) { if(angle===0)return imageDataCopy(image); const source=document.createElement('canvas'), target=document.createElement('canvas'); source.width=image.width; source.height=image.height; source.getContext('2d').putImageData(image,0,0); target.width=Math.abs(angle)===180?source.width:source.height; target.height=Math.abs(angle)===180?source.height:source.width; const ctx=target.getContext('2d'); if(angle===90){ctx.translate(target.width,0);ctx.rotate(Math.PI/2);} else if(Math.abs(angle)===180){ctx.translate(target.width,target.height);ctx.rotate(Math.PI);} else {ctx.translate(0,target.height);ctx.rotate(-Math.PI/2);} ctx.drawImage(source,0,0); return ctx.getImageData(0,0,target.width,target.height); }
function selectedResizeMode(){ return document.querySelector('input[name="resizeMode"]:checked')?.value || 'smooth'; }
function setResizeMode(mode){ const input=document.querySelector(`input[name="resizeMode"][value="${mode}"]`); if(input)input.checked=true; }
function resizeDimensions(image,scale){ return { width:Math.max(1,Math.round(image.width*scale)), height:Math.max(1,Math.round(image.height*scale)) }; }
function resizeImage(image,scale,mode){ const dimensions=resizeDimensions(image,scale), source=document.createElement('canvas'), target=document.createElement('canvas'); source.width=image.width; source.height=image.height; source.getContext('2d').putImageData(image,0,0); target.width=dimensions.width; target.height=dimensions.height; const ctx=target.getContext('2d'); ctx.imageSmoothingEnabled=mode==='smooth'; if(ctx.imageSmoothingEnabled)ctx.imageSmoothingQuality='high'; ctx.drawImage(source,0,0,dimensions.width,dimensions.height); return ctx.getImageData(0,0,dimensions.width,dimensions.height); }
async function defaultResizeMode(image,scale){ if(scale<1)return 'smooth'; const colorCount=await countUniqueColors(image); return colorCount<=256?'sharp':'smooth'; }
function setCurrent(image, name) { clearReductionState(); currentRotation=0; resizeModeTouched=false; setResizeMode('smooth'); if(els.resizeStatus)els.resizeStatus.textContent='Choose a scale to resize the current result.'; showCurrent(image,name); rotationSourceImage=imageDataCopy(currentImage); }
function setRotation(angle) { clearReductionState(); currentRotation=angle; showCurrent(rotateImage(rotationSourceImage,angle),angle?`${angle}° rotation`:'Rotation reset'); }
function commitCurrentEdit(image, name) { clearReductionState(); resizeModeTouched=false; showCurrent(image,name); rotationSourceImage=rotateImage(currentImage,-currentRotation); }
function centerSelection() { touchStart=null; const width=Math.min(originalImage.width, Math.max(64,Math.round(originalImage.width*.45))); const height=Math.min(originalImage.height, Math.max(64,Math.round(originalImage.height*.45))); selection={ x:Math.floor((originalImage.width-width)/2), y:Math.floor((originalImage.height-height)/2), width, height }; drawSelection(); schedulePreview(); }
function drawSelection() { selectionCtx.clearRect(0,0,els.selectionCanvas.width,els.selectionCanvas.height); if (!selection) return; selectionCtx.fillStyle='#087f6b22'; selectionCtx.strokeStyle='#087f6b'; selectionCtx.lineWidth=Math.max(2,Math.min(originalImage.width,originalImage.height)/250); selectionCtx.setLineDash([8,5]); selectionCtx.fillRect(selection.x,selection.y,selection.width,selection.height); selectionCtx.strokeRect(selection.x,selection.y,selection.width,selection.height); els.selectionInfo.textContent=touchStart?`Top-left corner selected at x ${touchStart.x}, y ${touchStart.y}. Tap the bottom-right corner.`:`Cleanup preview area: x ${selection.x}, y ${selection.y}, ${selection.width} × ${selection.height}px. Drag to select a different area, or tap the top-left and bottom-right corners on a touch screen.`; }
function pointerPosition(event) { const rect=els.selectionCanvas.getBoundingClientRect(); return { x:Math.max(0,Math.min(originalImage.width-1,Math.round((event.clientX-rect.left)*originalImage.width/rect.width))), y:Math.max(0,Math.min(originalImage.height-1,Math.round((event.clientY-rect.top)*originalImage.height/rect.height))) }; }
function selectionBetween(a,b) { return {x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.max(1,Math.abs(a.x-b.x)+1),height:Math.max(1,Math.abs(a.y-b.y)+1)}; }
els.selectionCanvas.addEventListener('pointerdown',e=>{ if(e.pointerType==='touch'){e.preventDefault();els.selectionCanvas.setPointerCapture(e.pointerId);return;} touchStart=null; dragStart=pointerPosition(e); els.selectionCanvas.setPointerCapture(e.pointerId); });
els.selectionCanvas.addEventListener('pointermove',e=>{ if(!dragStart)return; selection=selectionBetween(dragStart,pointerPosition(e)); drawSelection(); });
els.selectionCanvas.addEventListener('pointerup',e=>{ if(e.pointerType==='touch'){e.preventDefault();const p=pointerPosition(e); if(!touchStart){touchStart=p;selection=selectionBetween(p,p);drawSelection();return;} selection=selectionBetween(touchStart,p);touchStart=null;drawSelection();schedulePreview();return;} dragStart=null; schedulePreview(); });
els.selectionCanvas.addEventListener('pointercancel',()=>{ dragStart=null; });
els.resetSelection.addEventListener('click',centerSelection);

function schedulePreview(){ clearTimeout(debounceTimer); debounceTimer=setTimeout(updatePreview,180); }
async function updatePreview(){ if(!originalImage||!selection)return; const serial=++taskId; try { const crop=originalCtx.getImageData(selection.x,selection.y,selection.width,selection.height); setCanvasImage(els.cropOriginal,cropOriginalCtx,crop); els.cropCleaned.width=crop.width; els.cropCleaned.height=crop.height; const pixels=await runCleanup(crop,options()); if(serial+1!==taskId)return; cropCleanedCtx.putImageData(new ImageData(pixels,crop.width,crop.height),0,0); } catch(error){ fail(error); } }
['radius','threshold','minAgree','iterations'].forEach(id=>{ const output=$(`${id}Value`); els[id].addEventListener('input',()=>{ output.value=els[id].value; schedulePreview(); }); });
['includeAlpha','opaqueOnly'].forEach(id=>els[id].addEventListener('change',schedulePreview));
['alphaCutoff','sampleStep'].forEach(id=>{ const output=$(`${id}Value`); els[id].addEventListener('input',()=>{ output.value=els[id].value; clearReductionState(false); }); });
['reduceTargetColors','reduceDithering'].forEach(id=>els[id].addEventListener('change',()=>clearReductionState(false)));
els.reduceAlgorithm.addEventListener('change',()=>{ const popularity=els.reduceAlgorithm.value==='popularity'; els.sampleStepControl.classList.toggle('disabled-control',popularity); els.sampleStep.disabled=popularity; clearReductionState(false); });
els.reduceAlgorithm.dispatchEvent(new Event('change'));
async function previewReduction(){ if(!currentImage)throw new Error('Choose a PNG file first.'); if(!reductionTargetsAvailable)throw new Error('This image has no available smaller palette target.'); const generation=uploadGeneration, source=currentImage; busy('reducing the current palette'); const result=await runPaletteReduction(source,reductionOptions()); if(generation!==uploadGeneration||source!==currentImage)throw new Error('The image changed before palette reduction finished. Please preview again.'); reducedImage=result.image; reducedPaletteImage=result.indexed; setCanvasImage(els.reducePreviewCanvas,reducePreviewCtx,reducedImage); showReductionPalette(reducedPaletteImage); els.reduceStatus.textContent=reductionSummary(result); done('Reduced-color preview is ready.'); return result; }
els.previewReduced.addEventListener('click',async()=>{ try { await previewReduction(); } catch(error){ fail(error); } });
els.applyReduced.addEventListener('click',async()=>{ try { if(!reducedImage)await previewReduction(); const appliedIndexed={ palette:reducedPaletteImage.palette.map(color=>color.slice()), indices:new Uint8Array(reducedPaletteImage.indices) }; commitCurrentEdit(reducedImage,'Reduced-color PNG'); currentAppliedReduction={ indexed:appliedIndexed }; done('Palette reduction applied. The reduced PNG is selected for download.'); } catch(error){ fail(error); } });
els.downloadReduced.addEventListener('click',async()=>{ if(reducedImage&&reducedPaletteImage){ await downloadImage(reducedImage,'reduced-colors',reducedPaletteImage); return; } if(currentAppliedReduction&&currentImage){ await downloadImage(currentImage,'reduced-colors',currentAppliedReduction.indexed); return; } message('Preview or apply reduced colors before downloading the reduced PNG.','warn'); });

els.fileInput.addEventListener('change',async event=>{ const generation=++uploadGeneration, file=event.target.files[0]; if(!file){ message('No file selected.','warn'); disableButtons(false); return; } els.fileName.textContent=file.name; if(file.type!=='image/png'&&!file.name.toLowerCase().endsWith('.png'))return fail(new Error('Please choose a PNG file. Other image formats are not supported.')); try { busy('decoding PNG'); const bytes=await file.arrayBuffer(); if(generation!==uploadGeneration)return; if(!hasPngSignature(bytes))throw new Error('The selected file does not have a valid PNG signature.'); const bitmap=await createImageBitmap(file); if(generation!==uploadGeneration){bitmap.close();return;} if(bitmap.width*bitmap.height>20_000_000) message('Large image warning: processing this image may take a while.','warn'); els.originalCanvas.width=els.selectionCanvas.width=bitmap.width; els.originalCanvas.height=els.selectionCanvas.height=bitmap.height; originalCtx.clearRect(0,0,bitmap.width,bitmap.height); originalCtx.drawImage(bitmap,0,0); bitmap.close(); originalImage=originalCtx.getImageData(0,0,els.originalCanvas.width,els.originalCanvas.height); currentImage=imageDataCopy(originalImage); cleanedImage=null; clearReductionState(); const info=await parseChunks(bytes); if(generation!==uploadGeneration)return; originalPalette=info.ihdr?.colorType===3?info.palette:null; sourceFileName=file.name; els.usePalette.checked=!!originalPalette; setCurrent(originalImage,'Original image'); els.workspace.hidden=false; centerSelection(); renderScanlineVisualization(info,originalImage,generation); await renderMetadata(file,bytes,originalImage,generation); if(generation===uploadGeneration)done(`Loaded ${file.name}. Ready for local processing.`); } catch(error){ if(generation===uploadGeneration)fail(new Error(`Could not decode this PNG. ${error.message}`)); } });

els.applyCleanup.addEventListener('click',async()=>{ if(!originalImage)return fail(new Error('Choose a PNG file first.')); const generation=uploadGeneration, source=originalImage; try { busy('cleaning the whole image'); const pixels=await runCleanup(source,options()); if(generation!==uploadGeneration||source!==originalImage)return; cleanedImage=new ImageData(pixels,source.width,source.height); setCurrent(cleanedImage,'Cleaned PNG'); done('Cleanup complete. The cleaned PNG is selected for download.'); } catch(error){ if(generation===uploadGeneration)fail(error); } });
els.downloadCleaned.addEventListener('click',()=> cleanedImage ? downloadImage(cleanedImage,'cleaned') : message('Apply cleanup to the whole image before downloading the cleaned PNG.','warn'));
els.downloadCurrent.addEventListener('click',()=> currentImage ? downloadImage(currentImage,currentName.toLowerCase().replace(/[^a-z0-9]+/g,'-')) : message('Choose a PNG file first.','warn'));
els.usePalette.addEventListener('change',updatePaletteNote);
function crc32(bytes){let crc=-1;for(const byte of bytes){crc^=byte;for(let n=0;n<8;n++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^-1)>>>0;}
function pngChunk(type,data){const typeBytes=new TextEncoder().encode(type),chunk=new Uint8Array(data.length+12),view=new DataView(chunk.buffer);view.setUint32(0,data.length);chunk.set(typeBytes,4);chunk.set(data,8);view.setUint32(data.length+8,crc32(chunk.slice(4,data.length+8)));return chunk;}
async function deflate(bytes){const stream=new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate'));return new Uint8Array(await new Response(stream).arrayBuffer());}
async function encodeIndexedPng(image,indexed){
  const signature=new Uint8Array([137,80,78,71,13,10,26,10]), ihdr=new Uint8Array(13), view=new DataView(ihdr.buffer); view.setUint32(0,image.width);view.setUint32(4,image.height);ihdr[8]=8;ihdr[9]=3;
  const plte=new Uint8Array(indexed.palette.length*3),trns=new Uint8Array(indexed.palette.length); indexed.palette.forEach((color,i)=>{plte.set(color.slice(0,3),i*3);trns[i]=color[3];});
  const scanlines=new Uint8Array((image.width+1)*image.height);for(let y=0;y<image.height;y++)scanlines.set(indexed.indices.slice(y*image.width,(y+1)*image.width),y*(image.width+1)+1);
  const chunks=[signature,pngChunk('IHDR',ihdr),pngChunk('PLTE',plte)]; if(trns.some(alpha=>alpha<255))chunks.push(pngChunk('tRNS',trns)); chunks.push(pngChunk('IDAT',await deflate(scanlines)),pngChunk('IEND',new Uint8Array()));
  return new Blob(chunks,{type:'image/png'});
}
function downloadFileName(suffix){ const cleanName=sourceFileName.replace(/[\/]/g,'').trim()||'image.png', stem=cleanName.replace(/\.png$/i,''); return suffix==='original-image'?cleanName:`${stem}-${suffix}.png`; }
async function downloadImage(image,suffix,preferredIndexed=null){
  try { let blob; const indexed=preferredIndexed||(currentAppliedReduction&&currentImage===image?currentAppliedReduction.indexed:null)||(originalPalette&&els.usePalette.checked?paletteForImage(image):null); if(indexed){blob=await encodeIndexedPng(image,indexed);} else {const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').putImageData(normalizeTransparentPixels(imageDataCopy(image)),0,0);blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}
  if(!blob)return fail(new Error('Could not encode the PNG download.')); const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=downloadFileName(suffix);link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  } catch(error){fail(error);}
}

document.querySelectorAll('[data-rotate]').forEach(button=>button.addEventListener('click',()=>{ if(!rotationSourceImage)return fail(new Error('Choose a PNG file first.')); const angle=+button.dataset.rotate; busy(angle?`rotating to ${angle}°`:'resetting rotation'); requestAnimationFrame(()=>{ setRotation(angle); done(angle?`Created ${angle}° rotation. It is selected for download.`:'Reset rotation. The unrotated result is selected for download.'); }); }));

document.querySelectorAll('input[name="resizeMode"]').forEach(input=>input.addEventListener('change',()=>{ resizeModeTouched=true; }));
document.querySelectorAll('[data-resize]').forEach(button=>button.addEventListener('click',async()=>{ if(!currentImage)return fail(new Error('Choose a PNG file first.')); const scale=+button.dataset.resize, source=currentImage, from=`${source.width} × ${source.height}`, dimensions=resizeDimensions(source,scale), to=`${dimensions.width} × ${dimensions.height}`; try { busy(`resizing ${from}px to ${to}px`); if(!resizeModeTouched)setResizeMode(await defaultResizeMode(source,scale)); if(source!==currentImage)throw new Error('The image changed before resize started. Please try again.'); const mode=selectedResizeMode(); requestAnimationFrame(()=>{ const resized=resizeImage(source,scale,mode); commitCurrentEdit(resized,`${Math.round(scale*100)}% resize`); const label=mode==='sharp'?'Sharp / pixel-perfect':'Smooth'; const text=`Resized ${from}px to ${to}px using ${label}.`; els.resizeStatus.textContent=text; done(`${text} The resized PNG is selected for download.`); }); } catch(error){ fail(error); } }));

function dominantEdgeColor({width,height,data}){
  const counts=new Map(); let dominant=null, highest=0;
  const count=i=>{const p=i*4,key=`${data[p]},${data[p+1]},${data[p+2]}`, total=(counts.get(key)||0)+1; counts.set(key,total); if(total>highest){highest=total;dominant=[data[p],data[p+1],data[p+2]];}};
  for(let x=0;x<width;x++){count(x);if(height>1)count((height-1)*width+x);}
  for(let y=1;y<height-1;y++){count(y*width);if(width>1)count(y*width+width-1);}
  return dominant;
}
function hexColor(color){return `#${color.map(channel=>channel.toString(16).padStart(2,'0')).join('')}`;}
els.colorTolerance.addEventListener('input',()=>els.colorToleranceValue.value=els.colorTolerance.value); els.feather.addEventListener('input',()=>els.featherValue.value=els.feather.value);
els.removeConnected.addEventListener('click',()=>{ if(!currentImage)return fail(new Error('Choose a PNG file first.')); busy('finding and flood-filling the dominant exterior color'); requestAnimationFrame(()=>{ try { const image=imageDataCopy(currentImage), {width,height,data}=image, color=dominantEdgeColor(image), tolerance=+els.colorTolerance.value, limit=tolerance*tolerance*3, feather=+els.feather.value, seen=new Uint8Array(width*height), exterior=[]; const qualifies=i=>{const p=i*4,dr=data[p]-color[0],dg=data[p+1]-color[1],db=data[p+2]-color[2];return dr*dr+dg*dg+db*db<=limit;}; const queue=[]; const add=i=>{if(!seen[i]&&qualifies(i)){seen[i]=1;queue.push(i);}}; for(let x=0;x<width;x++){add(x);add((height-1)*width+x);} for(let y=0;y<height;y++){add(y*width);add(y*width+width-1);} for(let head=0;head<queue.length;head++){const i=queue[head],x=i%width,y=(i/width)|0; exterior.push(i); data[i*4]=data[i*4+1]=data[i*4+2]=data[i*4+3]=0; if(x)add(i-1);if(x+1<width)add(i+1);if(y)add(i-width);if(y+1<height)add(i+width);}
      if(feather){ let frontier=exterior; for(let layer=1;layer<=feather;layer++){const next=[]; for(const i of frontier){const x=i%width,y=(i/width)|0; for(const n of [x?i-1:-1,x+1<width?i+1:-1,y?i-width:-1,y+1<height?i+width:-1]) if(n>=0&&!seen[n]){seen[n]=1;next.push(n); data[n*4+3]=Math.min(data[n*4+3],Math.round(255*layer/(feather+1)));}} frontier=next; } }
      commitCurrentEdit(image,'Exterior connected color removed'); done(`Removed ${exterior.length.toLocaleString()} exterior pixels near dominant edge color ${hexColor(color)}. The result is selected for download.`); } catch(error){fail(error);} }); });

function hasPngSignature(buffer){ return [...new Uint8Array(buffer,0,8)].join(',')==='137,80,78,71,13,10,26,10'; }
const decodeLatin=(bytes)=>new TextDecoder('latin1').decode(bytes), decodeUtf8=(bytes)=>new TextDecoder().decode(bytes);
async function inflateRawBytes(bytes){ if(!('DecompressionStream' in window)) throw new Error('This browser cannot decompress PNG IDAT data for scanline visualization.'); try { const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate')); return new Uint8Array(await new Response(stream).arrayBuffer()); } catch { throw new Error('The PNG IDAT data could not be decompressed for scanline visualization.'); } }
async function inflate(bytes){ try { return decodeLatin(await inflateRawBytes(bytes)); } catch(error){ return error.message.includes('cannot decompress')?'[compressed text: this browser cannot decode zTXt]':'[compressed text could not be decoded]'; } }
function concatBytes(parts){ const length=parts.reduce((sum,part)=>sum+part.length,0), merged=new Uint8Array(length); let offset=0; for(const part of parts){ merged.set(part,offset); offset+=part.length; } return merged; }
async function parseChunks(buffer){ const view=new DataView(buffer), bytes=new Uint8Array(buffer), chunks=[], details={texts:[],idatParts:[],scanlineUnsupported:false}; let offset=8; while(offset+12<=buffer.byteLength){ const length=view.getUint32(offset), type=decodeLatin(bytes.slice(offset+4,offset+8)), data=bytes.slice(offset+8,offset+8+length); if(offset+12+length>buffer.byteLength)throw new Error('PNG chunk length exceeds file size.'); chunks.push({type,length}); if(type==='IHDR'){ details.ihdr={width:view.getUint32(offset+8),height:view.getUint32(offset+12),bitDepth:data[8],colorType:data[9],compression:data[10],filter:data[11],interlace:data[12]}; details.scanlineUnsupported=details.ihdr.interlace===1; } else if(type==='IDAT')details.idatParts.push(data); else if(type==='tEXt'){const n=data.indexOf(0);details.texts.push({type,key:decodeLatin(data.slice(0,n)),value:decodeLatin(data.slice(n+1))});} else if(type==='zTXt'){const n=data.indexOf(0);details.texts.push({type,key:decodeLatin(data.slice(0,n)),value:await inflate(data.slice(n+2))});} else if(type==='iTXt'){const keyEnd=data.indexOf(0), compressionFlag=data[keyEnd+1], languageStart=keyEnd+3, languageEnd=data.indexOf(0,languageStart), translatedEnd=data.indexOf(0,languageEnd+1), textStart=translatedEnd+1; details.texts.push({type,key:decodeLatin(data.slice(0,keyEnd)),value:compressionFlag===1?await inflate(data.slice(textStart)):decodeUtf8(data.slice(textStart))});} else if(type==='PLTE')details.palette=Array.from({length:data.length/3},(_,i)=>[data[i*3],data[i*3+1],data[i*3+2],255]); else if(type==='tRNS'&&details.palette)data.forEach((alpha,i)=>{if(details.palette[i])details.palette[i][3]=alpha;}); else if(type==='pHYs')details.phys={x:view.getUint32(offset+8),y:view.getUint32(offset+12),unit:data[8]?'pixels per metre':'unknown unit'}; else if(type==='gAMA')details.gamma=view.getUint32(offset+8)/100000; else if(type==='sRGB')details.srgb=data[0]; else if(type==='tIME')details.time=`${view.getUint16(offset+8)}-${String(data[2]).padStart(2,'0')}-${String(data[3]).padStart(2,'0')} ${String(data[4]).padStart(2,'0')}:${String(data[5]).padStart(2,'0')}:${String(data[6]).padStart(2,'0')} UTC`; offset+=length+12; if(type==='IEND')break; } details.chunks=chunks; return details; }
const scanlineFilters=[{name:'NONE',value:0,color:'#e53935',rgba:'rgba(229,57,53,.28)'},{name:'SUB',value:1,color:'#fb8c00',rgba:'rgba(251,140,0,.28)'},{name:'UP',value:2,color:'#1e88e5',rgba:'rgba(30,136,229,.28)'},{name:'AVERAGE',value:3,color:'#43a047',rgba:'rgba(67,160,71,.28)'},{name:'PAETH',value:4,color:'#8e24aa',rgba:'rgba(142,36,170,.28)'}];
function setScanlineStatus(text,kind=''){ els.scanlineStatus.textContent=text; els.scanlineStatus.className=`scanline-status ${kind}`; }
function resetScanlineVisualization(){ els.scanlineCanvas.width=0; els.scanlineCanvas.height=0; els.scanlineCounts.innerHTML=scanlineFilters.map(filter=>`<tr><th><span class="filter-swatch" style="--swatch:${filter.color}"></span>${filter.name} <code>${filter.value}</code></th><td>—</td></tr>`).join(''); }
function scanlineFilterRows(info, inflated){ const ihdr=info.ihdr; if(!ihdr)throw new Error('PNG header is missing, so scanline filters cannot be inspected.'); const samplesByColorType={0:1,2:3,3:1,4:2,6:4}, samples=samplesByColorType[ihdr.colorType]; if(!samples)throw new Error(`Color type ${ihdr.colorType} is not supported for scanline visualization.`); const rowByteLength=Math.ceil(ihdr.width*ihdr.bitDepth*samples/8), stride=rowByteLength+1, expected=stride*ihdr.height; if(inflated.length!==expected)throw new Error(`Unexpected decompressed IDAT size for scanline visualization: expected ${expected.toLocaleString()} bytes, got ${inflated.length.toLocaleString()}.`); const rows=[], counts=[0,0,0,0,0]; for(let y=0;y<ihdr.height;y++){ const filter=inflated[y*stride]; if(filter>4)throw new Error(`Invalid scanline filter byte ${filter} found on row ${y+1}.`); rows.push(filter); counts[filter]++; } return {rows,counts}; }
async function renderScanlineVisualization(info, originalImage, generation){ resetScanlineVisualization(); if(info.scanlineUnsupported||info.ihdr?.interlace===1){ setScanlineStatus('Scanline visualization is available for non-interlaced PNGs only.','warn'); return; } if(!info.idatParts?.length){ setScanlineStatus('No IDAT image data was found for scanline visualization.','error'); return; } setScanlineStatus('Reading scanline filter bytes…'); try { const inflated=await inflateRawBytes(concatBytes(info.idatParts)); if(generation!==uploadGeneration)return; const {rows,counts}=scanlineFilterRows(info,inflated); els.scanlineCanvas.width=originalImage.width; els.scanlineCanvas.height=originalImage.height; scanlineCtx.putImageData(imageDataCopy(originalImage),0,0); rows.forEach((filter,y)=>{ scanlineCtx.fillStyle=scanlineFilters[filter].rgba; scanlineCtx.fillRect(0,y,originalImage.width,1); }); els.scanlineCounts.innerHTML=scanlineFilters.map(filter=>`<tr><th><span class="filter-swatch" style="--swatch:${filter.color}"></span>${filter.name} <code>${filter.value}</code></th><td>${counts[filter.value].toLocaleString()}</td></tr>`).join(''); setScanlineStatus(`Visualized ${rows.length.toLocaleString()} non-interlaced scanlines.`); } catch(error){ if(generation===uploadGeneration)setScanlineStatus(error.message,'error'); } }

function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function chunkBadges(chunks){ const idats=chunks.filter(chunk=>chunk.type==='IDAT'); let renderedIdat=false; return chunks.flatMap(chunk=>{ if(chunk.type!=='IDAT')return [chunk]; if(renderedIdat)return []; renderedIdat=true; return [{...chunk,count:idats.length,length:idats.reduce((sum,idat)=>sum+idat.length,0)}]; }); }
async function renderMetadata(file,buffer,image,generation){
  const [info,uniqueCount]=await Promise.all([parseChunks(buffer),countUniqueColors(image)]);
  if(generation!==uploadGeneration)return;
  const ihdr=info.ihdr||{}, isPalette=ihdr.colorType===3, hasTransparency=image.data.some((value,index)=>index%4===3&&value<255);
  const colorTypes={0:'0 — grayscale',2:'2 — truecolor',3:'3 — indexed-color',4:'4 — grayscale + alpha',6:'6 — truecolor + alpha'};
  const rows=[['Filename',escapeHtml(file.name)],['File size',`${file.size.toLocaleString()} bytes`],['Decoded dimensions',`${image.width} × ${image.height}px`],['Unique decoded RGBA colors',uniqueCount.toLocaleString()],['PNG chunks',`<div class="chunk-list">${chunkBadges(info.chunks).map(c=>`<span class="chunk">${c.count>1?`${c.count} × `:''}${escapeHtml(c.type)} · ${c.length.toLocaleString()} B</span>`).join('')}</div>`],['IHDR width',ihdr.width],['IHDR height',ihdr.height],['IHDR bit depth',ihdr.bitDepth],['IHDR color type',colorTypes[ihdr.colorType]||ihdr.colorType],['IHDR compression method',ihdr.compression],['IHDR filter method',ihdr.filter],['IHDR interlace method',ihdr.interlace],['pHYs',info.phys?`${info.phys.x} × ${info.phys.y} ${info.phys.unit}`:'Not present'],['gAMA',info.gamma??'Not present'],['sRGB rendering intent',info.srgb??'Not present'],['tIME',info.time??'Not present'],['Text chunks',info.texts.length?info.texts.map(t=>`<strong>${escapeHtml(t.type)} · ${escapeHtml(t.key)}</strong>: ${escapeHtml(t.value)}`).join('<br>'):'None']];
  const highlights=[['Transparency',hasTransparency?'Yes':'No'],['Palette image',isPalette?'Yes':'No'],['Indexed colors',isPalette?info.palette.length.toLocaleString():'Not applicable']];
  const paletteDetails=isPalette?`<details class="metadata-palette"><summary>Palette colors (${info.palette.length.toLocaleString()})</summary>${paletteStrip(info.palette)}</details>`:'';
  els.metadata.innerHTML=`<dl class="metadata-highlights">${highlights.map(([key,value])=>`<div><dt>${key}</dt><dd>${value}</dd></div>`).join('')}</dl><details class="metadata-details"><summary>All metadata</summary><div class="metadata-details-body"><table>${rows.map(([key,value])=>`<tr><th>${escapeHtml(key)}</th><td>${value}</td></tr>`).join('')}</table>${paletteDetails}</div></details>`;
}
