'use strict';
const $ = (id) => document.getElementById(id);
const els = Object.fromEntries(['fileInput','fileName','message','workspace','originalCanvas','selectionCanvas','selectionInfo','resetSelection','cropOriginal','cropCleaned','radius','threshold','minAgree','iterations','includeAlpha','opaqueOnly','applyCleanup','downloadCleaned','resultCanvas','resultLabel','downloadCurrent','blackThreshold','blackThresholdValue','feather','featherValue','removeBlack','metadata'].map(id => [id,$(id)]));
const originalCtx = els.originalCanvas.getContext('2d', { willReadFrequently:true });
const selectionCtx = els.selectionCanvas.getContext('2d');
const resultCtx = els.resultCanvas.getContext('2d', { willReadFrequently:true });
const cropOriginalCtx = els.cropOriginal.getContext('2d', { willReadFrequently:true });
const cropCleanedCtx = els.cropCleaned.getContext('2d');
const worker = new Worker('worker.js');
let originalImage = null, currentImage = null, cleanedImage = null, currentName = 'result', selection = null, dragStart = null, taskId = 0, uploadGeneration = 0, debounceTimer;
const pending = new Map();
worker.onmessage = ({ data }) => { const request = pending.get(data.id); if (!request) return; pending.delete(data.id); data.error ? request.reject(new Error(data.error)) : request.resolve(data); };

function message(text, kind='') { els.message.textContent = text; els.message.className = `message ${kind}`; }
function disableButtons(disabled) { document.querySelectorAll('button').forEach(button => button.disabled = disabled); }
function busy(text) { message(`Working: ${text}…`); disableButtons(true); }
function done(text) { message(text); disableButtons(false); }
function fail(error) { message(error.message || String(error), 'error'); disableButtons(false); }
function imageDataCopy(image) { return new ImageData(new Uint8ClampedArray(image.data), image.width, image.height); }
function runCleanup(image, options) { return new Promise((resolve,reject) => { const id = ++taskId; const pixels = new Uint8ClampedArray(image.data); pending.set(id,{resolve:data=>resolve(new Uint8ClampedArray(data.pixels)),reject}); worker.postMessage({ id, action:'cleanup', pixels:pixels.buffer, width:image.width, height:image.height, options }, [pixels.buffer]); }); }
function countUniqueColors(image) { return new Promise((resolve,reject) => { const id = ++taskId; const pixels = new Uint8ClampedArray(image.data); pending.set(id,{resolve:data=>resolve(data.count),reject}); worker.postMessage({ id, action:'countColors', pixels:pixels.buffer }, [pixels.buffer]); }); }
function options() { return { radius:+els.radius.value, threshold:+els.threshold.value, minAgree:+els.minAgree.value, iterations:+els.iterations.value, includeAlpha:els.includeAlpha.checked, opaqueOnly:els.opaqueOnly.checked }; }
function setCanvasImage(canvas, ctx, image) { canvas.width=image.width; canvas.height=image.height; ctx.putImageData(image,0,0); }
function setCurrent(image, name) { currentImage=imageDataCopy(image); currentName=name; setCanvasImage(els.resultCanvas,resultCtx,currentImage); els.resultLabel.innerHTML=`Current download: <strong>${name}</strong> · ${image.width} × ${image.height}px`; }
function centerSelection() { const width=Math.min(originalImage.width, Math.max(64,Math.round(originalImage.width*.45))); const height=Math.min(originalImage.height, Math.max(64,Math.round(originalImage.height*.45))); selection={ x:Math.floor((originalImage.width-width)/2), y:Math.floor((originalImage.height-height)/2), width, height }; drawSelection(); schedulePreview(); }
function drawSelection() { selectionCtx.clearRect(0,0,els.selectionCanvas.width,els.selectionCanvas.height); if (!selection) return; selectionCtx.fillStyle='#087f6b22'; selectionCtx.strokeStyle='#087f6b'; selectionCtx.lineWidth=Math.max(2,Math.min(originalImage.width,originalImage.height)/250); selectionCtx.setLineDash([8,5]); selectionCtx.fillRect(selection.x,selection.y,selection.width,selection.height); selectionCtx.strokeRect(selection.x,selection.y,selection.width,selection.height); els.selectionInfo.textContent=`Cleanup preview area: x ${selection.x}, y ${selection.y}, ${selection.width} × ${selection.height}px. Drag to select a different area.`; }
function pointerPosition(event) { const rect=els.selectionCanvas.getBoundingClientRect(); return { x:Math.max(0,Math.min(originalImage.width-1,Math.round((event.clientX-rect.left)*originalImage.width/rect.width))), y:Math.max(0,Math.min(originalImage.height-1,Math.round((event.clientY-rect.top)*originalImage.height/rect.height))) }; }
els.selectionCanvas.addEventListener('pointerdown',e=>{ dragStart=pointerPosition(e); els.selectionCanvas.setPointerCapture(e.pointerId); });
els.selectionCanvas.addEventListener('pointermove',e=>{ if(!dragStart)return; const p=pointerPosition(e); selection={x:Math.min(p.x,dragStart.x),y:Math.min(p.y,dragStart.y),width:Math.max(1,Math.abs(p.x-dragStart.x)+1),height:Math.max(1,Math.abs(p.y-dragStart.y)+1)}; drawSelection(); });
els.selectionCanvas.addEventListener('pointerup',()=>{ dragStart=null; schedulePreview(); });
els.resetSelection.addEventListener('click',centerSelection);

function schedulePreview(){ clearTimeout(debounceTimer); debounceTimer=setTimeout(updatePreview,180); }
async function updatePreview(){ if(!originalImage||!selection)return; const serial=++taskId; try { const crop=originalCtx.getImageData(selection.x,selection.y,selection.width,selection.height); setCanvasImage(els.cropOriginal,cropOriginalCtx,crop); els.cropCleaned.width=crop.width; els.cropCleaned.height=crop.height; const pixels=await runCleanup(crop,options()); if(serial+1!==taskId)return; cropCleanedCtx.putImageData(new ImageData(pixels,crop.width,crop.height),0,0); } catch(error){ fail(error); } }
['radius','threshold','minAgree','iterations'].forEach(id=>{ const output=$(`${id}Value`); els[id].addEventListener('input',()=>{ output.value=els[id].value; schedulePreview(); }); });
['includeAlpha','opaqueOnly'].forEach(id=>els[id].addEventListener('change',schedulePreview));

els.fileInput.addEventListener('change',async event=>{ const generation=++uploadGeneration, file=event.target.files[0]; if(!file){ message('No file selected.','warn'); disableButtons(false); return; } els.fileName.textContent=file.name; if(file.type!=='image/png'&&!file.name.toLowerCase().endsWith('.png'))return fail(new Error('Please choose a PNG file. Other image formats are not supported.')); try { busy('decoding PNG'); const bytes=await file.arrayBuffer(); if(generation!==uploadGeneration)return; if(!hasPngSignature(bytes))throw new Error('The selected file does not have a valid PNG signature.'); const bitmap=await createImageBitmap(file); if(generation!==uploadGeneration){bitmap.close();return;} if(bitmap.width*bitmap.height>20_000_000) message('Large image warning: processing this image may take a while.','warn'); els.originalCanvas.width=els.selectionCanvas.width=bitmap.width; els.originalCanvas.height=els.selectionCanvas.height=bitmap.height; originalCtx.clearRect(0,0,bitmap.width,bitmap.height); originalCtx.drawImage(bitmap,0,0); bitmap.close(); originalImage=originalCtx.getImageData(0,0,els.originalCanvas.width,els.originalCanvas.height); currentImage=imageDataCopy(originalImage); cleanedImage=null; setCurrent(originalImage,'Original image'); els.workspace.hidden=false; centerSelection(); await renderMetadata(file,bytes,originalImage,generation); if(generation===uploadGeneration)done(`Loaded ${file.name}. Ready for local processing.`); } catch(error){ if(generation===uploadGeneration)fail(new Error(`Could not decode this PNG. ${error.message}`)); } });

els.applyCleanup.addEventListener('click',async()=>{ if(!originalImage)return fail(new Error('Choose a PNG file first.')); const generation=uploadGeneration, source=originalImage; try { busy('cleaning the whole image'); const pixels=await runCleanup(source,options()); if(generation!==uploadGeneration||source!==originalImage)return; cleanedImage=new ImageData(pixels,source.width,source.height); setCurrent(cleanedImage,'Cleaned PNG'); done('Cleanup complete. The cleaned PNG is selected for download.'); } catch(error){ if(generation===uploadGeneration)fail(error); } });
els.downloadCleaned.addEventListener('click',()=> cleanedImage ? downloadImage(cleanedImage,'cleaned') : message('Apply cleanup to the whole image before downloading the cleaned PNG.','warn'));
els.downloadCurrent.addEventListener('click',()=> currentImage ? downloadImage(currentImage,currentName.toLowerCase().replace(/[^a-z0-9]+/g,'-')) : message('Choose a PNG file first.','warn'));
function downloadImage(image,suffix){ const canvas=document.createElement('canvas'); canvas.width=image.width; canvas.height=image.height; canvas.getContext('2d').putImageData(image,0,0); canvas.toBlob(blob=>{ if(!blob)return fail(new Error('Could not encode the PNG download.')); const url=URL.createObjectURL(blob), link=document.createElement('a'); link.href=url; link.download=`pngtools-${suffix}.png`; link.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); },'image/png'); }

document.querySelectorAll('[data-rotate]').forEach(button=>button.addEventListener('click',()=>{ if(!currentImage)return fail(new Error('Choose a PNG file first.')); const angle=+button.dataset.rotate; busy(`rotating ${angle}°`); requestAnimationFrame(()=>{ const source=document.createElement('canvas'), target=document.createElement('canvas'); source.width=currentImage.width; source.height=currentImage.height; source.getContext('2d').putImageData(currentImage,0,0); target.width=angle===180?source.width:source.height; target.height=angle===180?source.height:source.width; const ctx=target.getContext('2d'); if(angle===90){ctx.translate(target.width,0);ctx.rotate(Math.PI/2);} else if(angle===180){ctx.translate(target.width,target.height);ctx.rotate(Math.PI);} else {ctx.translate(0,target.height);ctx.rotate(-Math.PI/2);} ctx.drawImage(source,0,0); setCurrent(ctx.getImageData(0,0,target.width,target.height),`${angle}° clockwise rotation`); done(`Created ${angle}° clockwise rotation. It is selected for download.`); }); }));

els.blackThreshold.addEventListener('input',()=>els.blackThresholdValue.value=els.blackThreshold.value); els.feather.addEventListener('input',()=>els.featherValue.value=els.feather.value);
els.removeBlack.addEventListener('click',()=>{ if(!currentImage)return fail(new Error('Choose a PNG file first.')); busy('flood-filling exterior near-black pixels'); requestAnimationFrame(()=>{ try { const image=imageDataCopy(currentImage), {width,height,data}=image, threshold=+els.blackThreshold.value, feather=+els.feather.value, seen=new Uint8Array(width*height), exterior=[]; const qualifies=i=>data[i*4]<=threshold&&data[i*4+1]<=threshold&&data[i*4+2]<=threshold; const queue=[]; const add=i=>{if(!seen[i]&&qualifies(i)){seen[i]=1;queue.push(i);}}; for(let x=0;x<width;x++){add(x);add((height-1)*width+x);} for(let y=0;y<height;y++){add(y*width);add(y*width+width-1);} for(let head=0;head<queue.length;head++){const i=queue[head],x=i%width,y=(i/width)|0; exterior.push(i); data[i*4+3]=0; if(x)add(i-1);if(x+1<width)add(i+1);if(y)add(i-width);if(y+1<height)add(i+width);}
      if(feather){ let frontier=exterior; for(let layer=1;layer<=feather;layer++){const next=[]; for(const i of frontier){const x=i%width,y=(i/width)|0; for(const n of [x?i-1:-1,x+1<width?i+1:-1,y?i-width:-1,y+1<height?i+width:-1]) if(n>=0&&!seen[n]){seen[n]=1;next.push(n); data[n*4+3]=Math.min(data[n*4+3],Math.round(255*layer/(feather+1)));}} frontier=next; } }
      setCurrent(image,'Exterior black removed'); done(`Removed ${exterior.length.toLocaleString()} exterior near-black pixels. The result is selected for download.`); } catch(error){fail(error);} }); });

function hasPngSignature(buffer){ return [...new Uint8Array(buffer,0,8)].join(',')==='137,80,78,71,13,10,26,10'; }
const decodeLatin=(bytes)=>new TextDecoder('latin1').decode(bytes), decodeUtf8=(bytes)=>new TextDecoder().decode(bytes);
async function inflate(bytes){ if(!('DecompressionStream' in window)) return '[compressed text: this browser cannot decode zTXt]'; try { const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate')); return decodeLatin(new Uint8Array(await new Response(stream).arrayBuffer())); } catch { return '[compressed text could not be decoded]'; } }
async function parseChunks(buffer){ const view=new DataView(buffer), bytes=new Uint8Array(buffer), chunks=[], details={texts:[]}; let offset=8; while(offset+12<=buffer.byteLength){ const length=view.getUint32(offset), type=decodeLatin(bytes.slice(offset+4,offset+8)), data=bytes.slice(offset+8,offset+8+length); if(offset+12+length>buffer.byteLength)throw new Error('PNG chunk length exceeds file size.'); chunks.push({type,length}); if(type==='IHDR') details.ihdr={width:view.getUint32(offset+8),height:view.getUint32(offset+12),bitDepth:data[8],colorType:data[9],compression:data[10],filter:data[11],interlace:data[12]}; else if(type==='tEXt'){const n=data.indexOf(0);details.texts.push({type,key:decodeLatin(data.slice(0,n)),value:decodeLatin(data.slice(n+1))});} else if(type==='zTXt'){const n=data.indexOf(0);details.texts.push({type,key:decodeLatin(data.slice(0,n)),value:await inflate(data.slice(n+2))});} else if(type==='iTXt'){const keyEnd=data.indexOf(0), compressionFlag=data[keyEnd+1], languageStart=keyEnd+3, languageEnd=data.indexOf(0,languageStart), translatedEnd=data.indexOf(0,languageEnd+1), textStart=translatedEnd+1; details.texts.push({type,key:decodeLatin(data.slice(0,keyEnd)),value:compressionFlag===1?await inflate(data.slice(textStart)):decodeUtf8(data.slice(textStart))});} else if(type==='pHYs')details.phys={x:view.getUint32(offset+8),y:view.getUint32(offset+12),unit:data[8]?'pixels per metre':'unknown unit'}; else if(type==='gAMA')details.gamma=view.getUint32(offset+8)/100000; else if(type==='sRGB')details.srgb=data[0]; else if(type==='tIME')details.time=`${view.getUint16(offset+8)}-${String(data[2]).padStart(2,'0')}-${String(data[3]).padStart(2,'0')} ${String(data[4]).padStart(2,'0')}:${String(data[5]).padStart(2,'0')}:${String(data[6]).padStart(2,'0')} UTC`; offset+=length+12; if(type==='IEND')break; } details.chunks=chunks; return details; }
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function renderMetadata(file,buffer,image,generation){ const [info,uniqueCount]=await Promise.all([parseChunks(buffer),countUniqueColors(image)]); if(generation!==uploadGeneration)return; const ihdr=info.ihdr||{}; const colorTypes={0:'0 — grayscale',2:'2 — truecolor',3:'3 — indexed-color',4:'4 — grayscale + alpha',6:'6 — truecolor + alpha'}; const rows=[['Filename',escapeHtml(file.name)],['File size',`${file.size.toLocaleString()} bytes`],['Decoded dimensions',`${image.width} × ${image.height}px`],['Unique decoded RGBA colors',uniqueCount.toLocaleString()],['PNG chunks',`<div class="chunk-list">${info.chunks.map(c=>`<span class="chunk">${escapeHtml(c.type)} · ${c.length.toLocaleString()} B</span>`).join('')}</div>`],['IHDR width',ihdr.width],['IHDR height',ihdr.height],['IHDR bit depth',ihdr.bitDepth],['IHDR color type',colorTypes[ihdr.colorType]||ihdr.colorType],['IHDR compression method',ihdr.compression],['IHDR filter method',ihdr.filter],['IHDR interlace method',ihdr.interlace],['pHYs',info.phys?`${info.phys.x} × ${info.phys.y} ${info.phys.unit}`:'Not present'],['gAMA',info.gamma??'Not present'],['sRGB rendering intent',info.srgb??'Not present'],['tIME',info.time??'Not present'],['Text chunks',info.texts.length?info.texts.map(t=>`<strong>${escapeHtml(t.type)} · ${escapeHtml(t.key)}</strong>: ${escapeHtml(t.value)}`).join('<br>'):'None']]; els.metadata.innerHTML=`<table>${rows.map(([key,value])=>`<tr><th>${escapeHtml(key)}</th><td>${value}</td></tr>`).join('')}</table>`; }
